version: '3.8'
services:
  frontend:
    container_name: towelshop-frontend
    build: ./
    image: "reactapp:1.0.0"
    networks:
      - ts-network
  backend:
    container_name: towelshop-backend
    build: ../backend
    image: "expressapp:1.0.0"
    networks:
      - ts-network
  revproxy:
    container_name: towelshop-proxy
    build: ../revproxy
    image: "reverseproxy:1.0.0"
    networks:
      - ts-network
    ports:
      - "8080:80"
networks:
  ts-network: