version: '2.0'
services:
  frontend:
    build: ./
    ports:
    - "3000:3000"
    depends_on:
    - backend
  backend:
    build: ../backend
    ports:
    - "5000:5000"
# To build it: docker-compose build
# To run it: docker-compose up